-- MySQL Script generated by MySQL Workbench
-- Wed May 13 23:42:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Document` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Document` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Connection_ID` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag_Text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tag_Text` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tag_Text` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Text` NVARCHAR(150) NOT NULL,
  `Tag_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Tag_Text_Tag_idx` (`Tag_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Tag_Text_Tag`
    FOREIGN KEY (`Tag_ID`)
    REFERENCES `mydb`.`Tag` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Connections` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Connections` (
  `Document_ID` INT NOT NULL,
  `Tag_Text_ID` INT NOT NULL,
  PRIMARY KEY (`Document_ID`, `Tag_Text_ID`),
  INDEX `fk_Document_has_Tag_Text_Tag_Text1_idx` (`Tag_Text_ID` ASC) VISIBLE,
  INDEX `fk_Document_has_Tag_Text_Document1_idx` (`Document_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Document_has_Tag_Text_Document1`
    FOREIGN KEY (`Document_ID`)
    REFERENCES `mydb`.`Document` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Document_has_Tag_Text_Tag_Text1`
    FOREIGN KEY (`Tag_Text_ID`)
    REFERENCES `mydb`.`Tag_Text` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
